name: Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # At 06:00 on day-of-month 1 in every month.
    - cron: "0 6 1 */1 *"

env:
  docker-image-name: ilcardella/rpi-pico-sdk
  push-docker-image: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' }}


jobs:
  docker:
    runs-on: ubuntu-latest
    name: Docker build and push

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        id: prepare
        run: |
          DOCKER_IMAGE=${{ env.docker-image-name }}
          VERSION=latest
          PLATFORMS=linux/amd64,linux/arm64
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          elif [[ $GITHUB_REF != refs/heads/main ]]; then
            VERSION=${GITHUB_REF#refs/heads/}
            VERSION=${VERSION##*/}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          fi

          echo "platforms=${PLATFORMS}" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: ${{ env.push-docker-image }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: ${{ steps.prepare.outputs.platforms }}
          push: ${{ env.push-docker-image }}
          tags: ${{ steps.prepare.outputs.tags }}

      - name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
